const AUTH_ACTION_TYPES = {
    REGISTER: "REGISTER",
    SET_USER_CREDENTIALS: "SET_USER_CREDENTIALS",
    UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
    INIT_LOGIN: "INIT_LOGIN",
    LOGIN: "LOGIN",
    SIGN_OUT: "SIGN_OUT",
};

export default AUTH_ACTION_TYPES;
