const MODAL_MUTATIONS_TYPES = {
    OPEN_MODAL: "OPEN_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL",
    SET_MODAL_NAME: "SET_MODAL_NAME",
    SET_MODAL_CONTEXT: "SET_MODAL_CONTEXT",
};

export default MODAL_MUTATIONS_TYPES;
