const MODAL_MUTATION_TYPES = {
    OPEN_MODAL: "OPEN_MODAL",
    CLOSE_MODAL: "CLOSE_MODAL",
    SET_NAME_MODAL: "SET_NAME_MODAL",
    SET_CONTEXT_MODAL: "SET_CONTEXT_MODAL",
};

export default MODAL_MUTATION_TYPES;
